# Generated by Django 6.0.4 on 2026-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_payout_idempotency_key_alter_payout_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(max_length=255),
        ),
    ]
