# Generated by Django 6.0.4 on 2026-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_alter_payout_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
